#!/usr/bin/env python3

import sys
import json


search_word = sys.argv[1]
try:
    dictionary = sys.argv[2]
except:
    dictionary = 'output/final.json'


with open(dictionary) as infile:
    dictionary = json.load(infile)


for outline, word in dictionary.items():
    if word == search_word:
        print(outline)
